services:
  mongodb:
    image: mongo:latest
    container_name: nojan-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nojan
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - nojan-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nojan-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/nojan?authSource=admin
    depends_on:
      - mongodb
    networks:
      - nojan-network
    volumes:
      - ./nojan-server:/app/nojan-server
      - /app/nojan-server/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nojan-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - nojan-network
    volumes:
      - ./nojan-client:/app/nojan-client
      - /app/nojan-client/node_modules
      - /app/nojan-client/.next

volumes:
  mongodb_data:

networks:
  nojan-network:
    driver: bridge
